sonar.projectName=rti-hemac
sonar.projectKey=rti-hemac
sonar.sources=src
sonar.tests=tests
# Language
sonar.language=py
sonar.python.version=3.11
sonar.exclusions=\
    **/venv/**/*,\
    .idea/**/*,\
    logs/**/*
sonar.projectDescription="RTI HeMac"
# Unit tests
sonar.python.xunit.reportPath=report.xml
sonar.python.coverage.reportPaths=coverage.xml
# lint
sonar.python.ruff.reportPaths=ruff-report.json
# dependencies
sonar.dependencyCheck.securityHotspot=true
sonar.dependencyCheck.htmlReportPath=dependency-check/dependency-check-report.html
sonar.dependencyCheck.xmlReportPath=dependency-check/dependency-check-report.xml
sonar.dependencyCheck.jsonReportPath=dependency-check/dependency-check-report.json
sonar.dependencyCheck.severity.high=7.0
sonar.dependencyCheck.severity.medium=4.0
sonar.dependencyCheck.severity.low=0.0

sonar.gitlab.failure_notification_mode=exit-code
sonar.gitlab.url=https://gitlab.thalesdigital.io

