(define (domain fleet_domain)
  (:requirements :typing)
  (:types quad observer location)
  (:predicates
    (at_quad ?q - quad ?loc - location)
    (at_obs ?o - observer ?loc - location)
    (adjacent ?loc1 - location ?loc2 - location)
    (target ?loc - location)
  )
  (:action move_quad
    :parameters (?q - quad ?from - location ?to - location)
    :precondition (and (at_quad ?q ?from) (adjacent ?from ?to))
    :effect (and (not (at_quad ?q ?from)) (at_quad ?q ?to))
  )
  (:action move_obs
    :parameters (?o - observer ?from - location ?to - location)
    :precondition (and (at_obs ?o ?from) (adjacent ?from ?to))
    :effect (and (not (at_obs ?o ?from)) (at_obs ?o ?to))
  )
)